# Generated by Django 6.0.2 on 2026-02-26 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_transaction_created_by_transaction_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['apartment', 'active', '-date'], name='main_transa_apartme_fa8704_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_debt', 'active'], name='main_transa_is_debt_0c545c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-updated_at'], name='main_transa_updated_d1d144_idx'),
        ),
    ]
