# Generated by Django 6.0.2 on 2026-02-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_transaction_active_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['apartment', 'active', '-date'], name='main_transa_apartme_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_debt', 'active'], name='main_transa_is_debt_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-updated_at'], name='main_transa_updated_idx'),
        ),
    ]
