# Generated by Django 6.0.2 on 2026-02-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_transaction_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='main_transa_apartme_fa8704_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='main_transa_is_debt_0c545c_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='main_transa_updated_d1d144_idx',
        ),
    ]
